### ISSUE TITLE
DEX version compatibility

### ISSUE THREAD

**Issue by privacyguy123** [google/smali#49] opened 2024-05-03 18:09 UTC
Does it matter, say, if I use a more recent version of smali/baksmali (DEX v41) to decompile/recompile a file that was compiled with DEX v38? Will this cause some sort of compatibility issues?

**Comment by sgjesse** [comment] 2024-05-06 08:26
The DEX version for the output of `smali` is indirectly determined by setting API level (`-a` or `--api`). See https://source.android.com/docs/core/runtime/dex-format#definitions for info on which android versions supports which DEX versions. See https://apilevels.com/ for which API level each Android version has.

DEX v41 is currently only supported for reading. Writing will never generate anything higher than v39.

**Comment by zerny** [comment] 2024-05-13 07:44
Closing as working as intended.

**Closed** 2024-05-13 07:45 UTC
